
language: java
sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker info
  - docker version

before_script:
  - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"

script:
  - make
  - make docker-tag

after_success:
  - make docker-push
