version: '3'
services:
  app:
    image: "virgil/mariadb-demo-server"
    expose:
      - "8080"
      - "8081"
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - server/.env
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/purekit?characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SERVER_SERVLET_CONTEXT_PATH: /api/v1/
      WAIT_HOSTS: mysql:3306
      spring_dbviewer_port: 8081
    depends_on:
      - mariadb
  client:
    image: "virgil/mariadb-demo-client"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - app
  mariadb:
    image: "mariadb:latest"
    environment:
      - MYSQL_DATABASE=purekit
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mariadbuser
      - MYSQL_PASSWORD=mariadbpwd
