version: '3'
services:
  server:
    image: "virgil/mariadb-demo-server"
    env_file:
      - server/.env
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/purekit?characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SERVER_SERVLET_CONTEXT_PATH: /api/v1/
      WAIT_HOSTS: mysql:3306
      spring_dbviewer_port: 8081
      spring_dbviewer_context: /db/
    depends_on:
      - mariadb
  client:
    image: "virgil/mariadb-demo-client"
    depends_on:
      - server
    expose:
      - "80"
    ports:
      - "80:80"
  mariadb:
    image: "mariadb:latest"
    environment:
      - MYSQL_DATABASE=purekit
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mariadbuser
      - MYSQL_PASSWORD=mariadbpwd
