mybatis:
   type-aliases-package: com.virgilsecurity.demo.purekit.server.model
   configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
spring:
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/purekit_demo?characterEncoding=UTF-8&serverTimezone=UTC
      username: purekit
      password: 1qaz2wsx
      initialize: true

#FIXME remove credentials
virgil:
  # Application ID
  appId: 
  # Application token. AT.****
  at: 
  # Nonrotatable master secret. NM.****
  nms: 
  # Backup public key. BU.****
  bu: 
  # App secret key. SK.****
  sk: 
  # Service public key. PK.**** 
  pk: 
  pheServiceAddress: https://api.virgilsecurity.com/phe/v1
  kmsServiceAddress: https://api.virgilsecurity.com/kms/v1
