mybatis:
   type-aliases-package: com.virgilsecurity.demo.purekit.server.model
   configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30
spring:
   datasource:
      driverClassName: org.hsqldb.jdbc.JDBCDriver
      url: jdbc:hsqldb:mem:testdb;sql.syntax_mys=true
      hikari:
         idle-timeout: 120000
         maximum-pool-size: 100
   flyway:
      locations: classpath:db/migration, classpath:db/special/mysql
